-- CreateTable
CREATE TABLE "receipts" (
    "id" STRING NOT NULL,
    "number" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "date" TIMESTAMP(6) NOT NULL,
    "value" DECIMAL(65,30) NOT NULL,
    "historic" STRING,
    "recipientName" STRING NOT NULL,
    "recipientAddress" STRING,
    "recipientDocument" STRING,
    "payerName" STRING,
    "payerAddress" STRING,
    "payerDocument" STRING,

    CONSTRAINT "receipts_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "receipts_number_key" ON "receipts"("number");
